export const LESSONS = [
  { id: "l01", title: "What is cloning?", body: "A clone is an organism with the same nuclear DNA as another organism. Cloning is how that copy is produced — by mitosis, not by mixing two gametes.", try: "define", quiz: 0 },
  { id: "l02", title: "Genetically identical", body: "Same nuclear genes / same DNA sequence in the nucleus. Mitochondria in SCNT usually come from the egg cytoplasm, so they can differ. Same genes ≠ identical lives.", try: "define" },
  { id: "l03", title: "Natural cloning", body: "Asexual reproduction copies a genome by mitosis: runners, bulbs, tubers, cuttings, binary fission, and identical twins after an embryo splits.", try: "plant" },
  { id: "l04", title: "Identical twins", body: "One zygote divides; the embryo splits. Both twins match that zygote’s genome. They are natural clones of each other — not copies of a chosen adult.", try: "define" },
  { id: "l05", title: "Artificial cloning", body: "Humans copy genomes on purpose: tissue culture, embryo splitting, SCNT, and growing transgenic microbes. The genetic idea is still mitosis.", try: "scnt" },
  { id: "l06", title: "Plant cloning", body: "Many plant cells stay totipotent. A small piece of tissue can rebuild a whole plant, genetically identical to the parent (5.17B / 5.18B).", try: "plant" },
  { id: "l07", title: "Tissue culture", body: "Explant → surface sterilise → in vitro nutrient medium + hormones → callus / plantlets → transplant and acclimatise. Dirty technique causes contamination.", try: "plant", exam: 6 },
  { id: "l08", title: "Advantages of plant cloning", body: "Fast production of many plants with a desired characteristic; useful rare plants; all keep the parent’s nuclear genes.", try: "plant" },
  { id: "l09", title: "Disadvantages of plant cloning", body: "Low genetic variation. A disease or environmental change can hit the whole crop. Sterile labs are expensive.", try: "plant" },
  { id: "l10", title: "Animal cloning", body: "Adult mammal cells are not totipotent. SCNT puts a somatic nucleus into an enucleated egg so an embryo can form and a surrogate can carry it.", try: "scnt" },
  { id: "l11", title: "Somatic cell nuclear transfer", body: "Diploid nucleus from a mature body cell → enucleated unfertilised egg → electric pulse activates mitosis → embryo → surrogate (5.19B).", try: "scnt", exam: 2 },
  { id: "l12", title: "The donor cell", body: "A differentiated somatic cell. Its nucleus still holds a complete diploid genome — that is the genome you copy.", try: "scnt" },
  { id: "l13", title: "The egg cell", body: "An unfertilised egg. Cytoplasm can reprogramme the somatic nucleus. Its own haploid nucleus must be removed.", try: "scnt" },
  { id: "l14", title: "Enucleation", body: "Remove the egg nucleus so two genomes do not mix and the chromosome number stays diploid from the donor only.", try: "scnt", quiz: 2, exam: 1 },
  { id: "l15", title: "Nuclear transfer", body: "The donor nucleus is placed into the enucleated egg. This reconstructed oocyte has donor nuclear DNA in egg cytoplasm.", try: "scnt" },
  { id: "l16", title: "Activation", body: "A brief electric pulse starts the cell dividing. It does not create DNA or add genes.", try: "scnt" },
  { id: "l17", title: "Embryo development", body: "Mitosis: 1 → 2 → 4 → 8 cells → morula → blastocyst. Every nucleus matches the somatic donor.", try: "scnt" },
  { id: "l18", title: "Surrogate", body: "She provides the uterus. She is not the nuclear parent. The clone does not match her nuclear DNA.", try: "dolly", quiz: 3, exam: 3 },
  { id: "l19", title: "Why the clone matches the donor", body: "Nuclear DNA came from the somatic nucleus and was copied by mitosis. The egg nucleus was removed. The surrogate donated no nuclear genes.", try: "dolly" },
  { id: "l20", title: "Environmental effects", body: "Phenotype = genotype + environment. Clones can still differ in size, health and behaviour if conditions differ.", try: "define" },
  { id: "l21", title: "Embryo splitting", body: "An early embryo is divided. The pieces are genetically identical to each other (and to that embryo), not necessarily to a chosen adult.", quiz: 5 },
  { id: "l22", title: "SCNT vs embryo splitting", body: "SCNT copies a known adult’s somatic nucleus. Splitting copies whatever genome that embryo already had.", try: "scnt" },
  { id: "l23", title: "Bacterial cloning", body: "Binary fission: DNA replicates, the cell elongates, a septum forms, two descendants. A colony is a clonal population until mutation.", try: "bacteria" },
  { id: "l24", title: "Applications", body: "Crops with a useful trait; research animals; conservation of cells; transgenic animals producing a human protein; insulin from microbes.", try: "transgenic" },
  { id: "l25", title: "Advantages", body: "Copy a proven genotype quickly. Keep a transgenic gene that sexual breeding might shuffle away.", exam: 4 },
  { id: "l26", title: "Disadvantages", body: "Low success in mammals, welfare cost, expense, reduced variation, ethical objections to reproductive cloning.", exam: 4 },
  { id: "l27", title: "Genetic variation", body: "Sexual reproduction shuffles alleles. Cloning does not. Many individuals share one genome.", quiz: 4, exam: 5 },
  { id: "l28", title: "Disease vulnerability", body: "If clones share one immune genotype, a pathogen or environmental change can affect all of them.", exam: 5 },
  { id: "l29", title: "Ethics", body: "4BI1 wants a discussion, not a sermon. Typical tensions: conservation vs low variation; medical transgenic clones vs animal welfare; crop uniformity vs disease; human reproductive cloning (widely banned). Always name who benefits and who pays.", try: "ethics" },
  { id: "l30", title: "Transgenic organisms", body: "A gene from another species is present in the genome. That organism is transgenic (5.16 / 5.20B).", try: "transgenic" },
  { id: "l31", title: "Transgenic cloning", body: "Once the gene is in the host, cloning/reproduction copies the modified genome so the trait is not lost to meiosis.", try: "transgenic" },
  { id: "l32", title: "Human insulin", body: "The human insulin gene is introduced into a microorganism. The host is cloned; the culture produces insulin. This is a concept model, not a molecular-scale lab.", try: "transgenic", exam: 7 },
  { id: "l33", title: "Exam technique", body: "Use: genetically identical / nuclear DNA / diploid somatic nucleus / enucleated egg / electric pulse / mitosis / embryo / surrogate / explant / sterilise.", try: "exam" },
  { id: "l34", title: "Final challenge", body: "Choose the method from the biological problem, then perform it with no procedure sheet.", try: "master" }
];

export const GLOSSARY = [
  ["clone", "Organism (or cell) genetically identical in its nuclear DNA to another."],
  ["genetically identical", "Same nuclear genes / same DNA sequence in the nucleus."],
  ["somatic cell", "A body cell, not a gamete. Used as the nuclear donor in SCNT."],
  ["nucleus", "Contains chromosomes — the nuclear genome that cloning copies."],
  ["enucleated", "The nucleus has been removed (from the egg, in SCNT)."],
  ["nuclear transfer", "Moving a donor nucleus into an enucleated egg."],
  ["embryo", "Ball of cells after the reconstructed egg divides by mitosis."],
  ["surrogate", "Female who carries the pregnancy; not the nuclear parent."],
  ["tissue culture", "Growing plants from explants on sterile nutrient medium in vitro."],
  ["explant", "Small piece of plant tissue used to start a culture."],
  ["micropropagation", "Rapid cloning of plants by tissue culture."],
  ["binary fission", "Bacterial asexual reproduction: DNA copy, elongate, split."],
  ["transgenic", "Contains a gene that originated in another species."],
  ["genetic variation", "Differences in alleles in a population. Cloning reduces it."],
  ["totipotent", "Able to develop into any cell type / a whole organism. Many plant cells remain totipotent."],
  ["diploid", "Two sets of chromosomes. A somatic nucleus is diploid; an unfertilised egg nucleus is haploid."],
  ["blastocyst", "Hollow ball of cells after the morula. Often the stage transferred to a surrogate."],
  ["callus", "Mass of unspecialised plant cells that can form plantlets in culture."],
  ["ethics", "Judgements about what ought to be done. 4BI1 expects advantages, disadvantages and discussion — not one ‘correct’ opinion."]
];

export const ETHICS = [
  {
    id: "wild",
    tag: "Conservation",
    spec: "Variation · 5.19B",
    title: "Twelve individuals left. Clone them?",
    scene: "A mammal is down to a dozen animals. Biologists can take somatic cells, make SCNT embryos, and raise numbers quickly. The habitat that failed them is still damaged.",
    yes: { k: "Clone to buy time", t: "Stored cells can raise headcount. A clone is still only one genome wearing many bodies." },
    no: { k: "Do not clone", t: "You multiply one immune system. A disease or further habitat loss can finish the lot." },
    mid: { k: "A tool, not a rescue", t: "Clone while you restore habitat and, if possible, breed between remaining lineages." },
    for: ["Can increase numbers from banked cells", "May keep a genotype that would otherwise vanish", "Buys time while habitat is repaired"],
    against: ["Clones share one nuclear genome — low variation", "A pathogen can hit every copy", "Does not replace ecosystems, prey, or culture of wild behaviour"],
    exam: "Discuss: cloning may conserve a genotype (1) but reduces genetic variation / disease risk (1). Habitat still required (1)."
  },
  {
    id: "pharm",
    tag: "Transgenic animals",
    spec: "5.16 / 5.20B",
    title: "Clone a transgenic ewe that secretes a human protein in milk?",
    scene: "A human gene is already in one animal. Sexual breeding might shuffle it away. Cloning copies the useful transgenic genome. Many reconstructed eggs still fail.",
    yes: { k: "Clone the producer", t: "Keeps the inserted gene. Patients can receive a protein that is otherwise scarce." },
    no: { k: "Do not clone her", t: "Failed pregnancies and abnormal clones are a welfare cost paid for a medical product." },
    mid: { k: "Only under licence", t: "Allowed where regulation, veterinary care and a clear medical need exist — not as a farm fashion." },
    for: ["Copies a proven transgenic genotype", "Avoids losing the gene to meiosis", "Can supply a human therapeutic protein"],
    against: ["Low success of mammalian SCNT", "Surrogate and clone welfare", "Public trust if animals are treated as factories"],
    exam: "Advantage: keep a useful / transgenic characteristic. Disadvantage: ethics, welfare, cost, low success. Use those words."
  },
  {
    id: "herd",
    tag: "Agriculture",
    spec: "Genetic variation",
    title: "Clone a prize dairy cow into a whole herd?",
    scene: "One cow yields exceptional milk. A company offers a barn of her clones. Every animal would share her nuclear DNA — and her weaknesses.",
    yes: { k: "Copy the yield", t: "Fast production of a proven genotype. No wait for generations of selective breeding." },
    no: { k: "Keep a mixed herd", t: "One mastitis strain or feed change can hit every clone. Variation is a biological insurance policy." },
    mid: { k: "A few clones, not the herd", t: "Research or nucleus-herd clones, still crossed with other lines for the commercial flock." },
    for: ["Desirable characteristic copied quickly", "Predictable production traits", "Useful for research animals with a known genome"],
    against: ["Narrow gene pool", "Shared susceptibility to disease", "Does not create new alleles — only copies"],
    exam: "Cloning reduces variation because many individuals have the same alleles (1). A change in conditions / disease may affect all of them (1)."
  },
  {
    id: "human",
    tag: "Human cloning",
    spec: "Law · welfare",
    title: "Should a human be produced by SCNT?",
    scene: "The biology is the same idea as Dolly: a somatic nucleus in an enucleated egg. Almost every country bans reproductive cloning of people. Therapeutic use of cloned cells is a different debate.",
    yes: { k: "Allow reproductive cloning", t: "A minority argue reproductive freedom. Mark schemes still expect you to know it is widely illegal and unsafe." },
    no: { k: "Ban reproductive cloning", t: "High failure, unknown health of any child, identity questions, and explicit legal bans." },
    mid: { k: "Cells, not people", t: "Some research uses nuclear transfer to make matched cells for study. That is not the same as implanting a human embryo to birth." },
    for: ["Theoretical: genetically matched cells for research", "Some families might want a genetic copy — this is not an IGCSE ‘yes’"],
    against: ["Very low success and likely suffering", "Identity, consent of the future person", "Widely banned — state this in an exam"],
    exam: "State that human reproductive cloning is widely banned. Separate it from cloning cells / transgenic microbes. Discuss welfare and ethics."
  },
  {
    id: "crop",
    tag: "Plant cloning",
    spec: "5.17B / 5.18B",
    title: "Plant an entire orchard from one elite tree?",
    scene: "Tissue culture can fill a valley with genetically identical trees that all fruit well. A new fungus arrives that those trees cannot resist.",
    yes: { k: "Plant the clones", t: "Fast, uniform crop with the desired characteristic. Rare plants can be multiplied." },
    no: { k: "Mix the genotypes", t: "A monoclonal orchard is one infection away from collapse. Sexual seedlings keep alleles in play." },
    mid: { k: "Clones plus diversity strips", t: "Use micropropagation for the elite line, but interplant other cultivars and wild relatives." },
    for: ["Rapid production of a desired plant", "All keep the parent’s nuclear genes", "Useful for rare or sterile cultivars"],
    against: ["Low genetic variation in the crop", "Disease or climate change can hit all plants", "Sterile labs are expensive"],
    exam: "Advantage of plant cloning: many plants with a desired characteristic. Disadvantage: reduced variation / disease can spread."
  },
  {
    id: "pet",
    tag: "Companion animals",
    spec: "Same genes ≠ same pet",
    title: "Clone a dead dog so the owner ‘gets them back’?",
    scene: "A company offers SCNT from a skin sample. Nuclear DNA can match. The puppy will not remember the old dog. Surrogates still carry the pregnancy.",
    yes: { k: "Make the copy", t: "The owner receives an animal with the same nuclear genes. Appearance may be close." },
    no: { k: "Refuse the clone", t: "It is a new animal. Grief is not solved by mitosis. Welfare of surrogates and failed embryos remains." },
    mid: { k: "Be honest in the sale", t: "If it happens at all, the science must be explained: same genes, not the same life, not the same mind." },
    for: ["Nuclear DNA can match a valued animal", "Might preserve a rare breed genotype"],
    against: ["Phenotype still meets a new environment", "Not a resurrection — no copied memories", "Commercial pressure vs animal welfare"],
    exam: "Same nuclear DNA does not mean identical behaviour or health. Environment still acts. Surrogate ≠ nuclear parent."
  },
  {
    id: "dollyw",
    tag: "Animal welfare",
    spec: "5.19B success rate",
    title: "Dolly took hundreds of reconstructed eggs. Is that acceptable?",
    scene: "Mammalian SCNT wastes many embryos. Some clones have been unhealthy. The science taught us reprogramming; the cost was paid by animals that never became news.",
    yes: { k: "The knowledge was worth it", t: "One famous clone taught nuclear reprogramming and later medical ideas. Science often has a body count in its history." },
    no: { k: "The cost is too high", t: "A technique with tiny success and sick offspring should not be routine, even for research fame." },
    mid: { k: "Tighten, don’t mythologise", t: "Use the history to demand better welfare rules, and never pretend electricity ‘creates life’ without failed attempts." },
    for: ["Advanced understanding of development", "Enabled later transgenic / stem-cell research", "Agricultural and medical spin-offs"],
    against: ["Many failed embryos and pregnancies", "Possible health problems in clones", "Public trust if suffering is hidden"],
    exam: "Disadvantage of cloning mammals: low success / ethical issues / welfare / expensive. Name at least one."
  },
  {
    id: "research",
    tag: "Research animals",
    spec: "Controls",
    title: "Clone mice so every experiment uses the ‘same’ animal?",
    scene: "Scientists want genetically identical animals so drug tests are not confounded by allele differences. The colony is a clone army of one genome.",
    yes: { k: "Standardise the genome", t: "Fairer comparisons. Fewer animals might be needed if noise from genetics falls." },
    no: { k: "Keep genetic spread", t: "A drug that works only on one genome may fail in real, variable humans. Uniform mice can mislead." },
    mid: { k: "Both kinds of colony", t: "Inbred/clonal lines for mechanism; outbred animals before anyone claims a human treatment." },
    for: ["Controlled genotype for fair tests", "Repeatable results", "Can reduce some sources of experimental noise"],
    against: ["Results may not generalise", "Welfare of producing the colony", "Still not a copy of human genetic diversity"],
    exam: "Clones are useful as genetically identical controls, but reduced variation is also why results may not apply to a mixed population."
  }
];
